### ISSUE TITLE
OnlineAnonymity速度极快，占用似乎稍大

### ISSUE THREAD

**Issue by cypcym** [dodois/Doisnet#13]
YouTube 4k流畅观看。稳定性极佳，使用近一天无掉线。

占用似乎稍大，连接时笔记本风扇即时加速，忽忽直转。能否改善一下?
另外，能不能增加随系统启动，自动连接vpn功能。就不用每次手动打开了。

再次感谢作者，非常好用！

**Comment by dodois** [comment]
@cypcym 谢谢反馈 
1. 占用似乎稍大？ 我们默认开启了硬件加速，目的是为了提升 Doisnet 的使用流畅度。我们将在```0.0.7```版本的设置中心添加一个可配置项 ```启用硬件加速``` ，如果希望降低GPU使用效率，可以在后续版本关闭此选项。
2. 能不能增加随系统启动？0.0.7版本同时会上线 ```插件随系统启动``` 功能

**Comment by cypcym** [comment]
感谢解答。
刚试了一下，GPU高占用主要出现在ui界面打开的时候。关闭界面就恢复正常。希望这点发现，对您的优化能有所帮助。
期待新版本的上线，再次感谢。

**Comment by cypcym** [comment]
能否增加vpn线路选择功能？

**Comment by dodois** [comment]
> 能否增加vpn线路选择功能？

计划之中但未提上日程
