### ISSUE TITLE
一直显示“断开中”

### ISSUE THREAD

**Issue by allentown521** [dodois/Doisnet#14]
关闭程序，卸载（完整删除）重装都不行。
![image](https://user-images.githubusercontent.com/69662387/119623028-5ba73f00-be3a-11eb-9ae7-439a9abcea57.png)

**Comment by allentown521** [comment]
我删除了C:\Users\Administrator\AppData\Roaming\doisnet目录就好了

**Comment by dodois** [comment]
@allentown521 感谢反馈，我们已经将此bug提上日程，并将在0.0.7版本中修复
