### ISSUE TITLE
不停弹窗报错

### ISSUE THREAD

**Issue by allentown521** [dodois/Doisnet#15]
![image](https://user-images.githubusercontent.com/69662387/120128565-e4d0c400-c1f4-11eb-9101-2d41a265919f.png)
![image](https://user-images.githubusercontent.com/69662387/120128573-e8fce180-c1f4-11eb-8392-6c88c899400b.png)
早上更新到最新版就这样了，用了一会不停弹窗

**Comment by dodois** [comment]
@allentown521 感谢反馈，0.0.8版本马上会上线，修复了错误弹窗问题

**Comment by allentown521** [comment]
![image](https://user-images.githubusercontent.com/69662387/120146223-5457ab00-c217-11eb-88d6-5a84d2dd7f29.png)
升级到0.0.8了，但是还有弹窗，是不是应该全局捕获异常

**Comment by dodois** [comment]
@allentown521 谢谢反馈，准备上0.0.9版本了 👍
