### ISSUE TITLE
已更新，希望能解决cpu占用的问题

### ISSUE THREAD

**Issue by cypcym** [dodois/Doisnet#16]
![image](https://user-images.githubusercontent.com/46094731/120139397-f6bd6180-c20a-11eb-95f9-003ec05ceff7.png)
已更新至0.8版。但cpu占用还是比较大的（11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz），硬件加速开关作用不明显。笔记本风扇一直转很影响使用体验。
不确定是不是个例。
当然，软件本身还是一如既往的好用，非常感谢作者。

**Comment by cypcym** [comment]
![image](https://user-images.githubusercontent.com/46094731/120140076-56683c80-c20c-11eb-8e42-b76388435daa.png)
观察了一阵，持续在25%的占用上。

**Comment by dodois** [comment]
@cypcym 谢谢反馈，已收到，硬件加速关闭后GPU显著下降，但软件显示需要耗费的资源会转移到CPU，另外CPU问题与禁止插件广告有关，我们目前强制禁止了第三方插件发布及推送小广告的能力，有关此问题的更多解释将在后续版本跟进。
