### ISSUE TITLE
能否增加智能代理 网址白名单

### ISSUE THREAD

**Issue by allentown521** [dodois/Doisnet#17]
虽然智能代码大部分场景下能够稳定使用，但是某些网址（目前我发现gitlab）使用了智能代理后访问不太正常，能否增加一个白名单设置，白名单部分的网址不走代理

**Comment by dodois** [comment]
> 虽然智能代码大部分场景下能够稳定使用，但是某些网址（目前我发现gitlab）使用了智能代理后访问不太正常，能否增加一个白名单设置，白名单部分的网址不走代理
将在未来更新中实现

**Comment by allentown521** [comment]
很棒的软件，期待手机端
![image](https://user-images.githubusercontent.com/69662387/120290285-c6ea8880-c2f4-11eb-8259-8645d07706aa.png)
