### ISSUE TITLE
什么时候能出mac版本的？

### ISSUE THREAD

**Issue by bugfix2020** [dodois/Doisnet#2]
如题

**Comment by dodois** [comment]
@bugfix2020 mac版本已经在测试中了，如果测试正常，今天晚点会上传mac版

**Comment by dodois** [comment]
### 我们缺少可用的苹果开发者ID

该问题导致Mac版 [Doisnet](https://github.com/dodois/Doisnet) 无法正常签名打包.
希望社区的小伙伴能够支援我们有效的开发者ID或证书.
助力Mac版 [Doisnet](https://github.com/dodois/Doisnet) 早日上线.

### 支援方式：
1. 加入 [TG群组](https://t.me/dosvpn)
2. 邮件 <doisnet@protonmail.com>
