### ISSUE TITLE
下载链接无法打开

### ISSUE THREAD

**Issue by COD-ui** [dodois/Doisnet#26]
请问在哪里下载

**Comment by dodois** [comment]
下载地址: 
1. http://dlj.bz/doisnet
2. https://fastgit.org/dodois/Doisnet/releases/download/v0.1.4/doisnet-0.1.4.Setup.exe
3. https://github.com/dodois/Doisnet/releases/download/v0.1.4/doisnet-0.1.4.Setup.exe
