### ISSUE TITLE
邀请原本已满，怎么最近又显示没邀请够？

### ISSUE THREAD

**Issue by cypcym** [dodois/Doisnet#31]
邀请已满，自由节点功能也正常使用好多天，并绑定了邮箱。
昨日登陆时，自由节点菜单变灰，邀请界面显示只邀请了3人（今日打开后又显示成1人了）。

**Comment by dodois** [comment]
您好，感谢反馈！关于此现象我们在8月16日在应用内部进行了通知，以下是通知内容：
2021-08-16 12:32:57 杜绝刷注册，刷邀请人数的行为
为了杜绝此类现象我们后续将会清理超过15天未登录且未绑定邮箱的账号！感谢小伙伴们对Doisnet的支持！

**Comment by cypcym** [comment]
对方15天未登录，我这就成无效邀请了？
这个，这个，我有点难......
行吧，谢谢你，软件还是很好用的
