### ISSUE TITLE
连接后网站上不去,开启全局后直接断网

### ISSUE THREAD

**Issue by 1235689hhh** [dodois/Doisnet#33]

**Comment by dodois** [comment]
今日部分节点故障，正在排查并全力修复

**Comment by ChasionNo1** [comment]
今天也是如此

**Comment by dodois** [comment]
官方节点故障，正在维护中，预计0.2.0上线时修复，请使用【自由选择节点】进行过渡。非常抱歉出现此问题，我们已经对【自由选择节点】的捐赠门槛进行大幅降低，请有能力的小伙伴采用捐赠对Doisnet提供支持，谢谢！

**Comment by xiaochengzi6** [comment]
> 官方节点故障，正在维护中，预计0.2.0上线时修复，请使用【自由选择节点】进行过渡。非常抱歉出现此问题，我们已经对【自由选择节点】的捐赠门槛进行大幅降低，请有能力的小伙伴采用捐赠对Doisnet提供支持，谢谢！

我很支持这种免费的梯子我也愿意为它采用捐赠的方式提供的支持但是我更想了解到的它能不能更加长久和保持一定的稳定性。

**Comment by cypcym** [comment]
免费如果有困难的话，建议直接改为收费模式。
