### ISSUE TITLE
git提交代码到github的时候可以使用这个吗，应该如何设置？

### ISSUE THREAD

**Issue by yexian-01** [dodois/Doisnet#37]

**Comment by dodois** [comment]
```git config --global http.proxy 'socks5://127.0.0.1:8000'```

**Comment by yexian-01** [comment]
谢谢

**Comment by yexian-01** [comment]
> `git config --global http.proxy 'socks5://127.0.0.1:8000'`

**Comment by yexian-01** [comment]
> `git config --global http.proxy 'socks5://127.0.0.1:8000'`

谢谢
