### ISSUE TITLE
失效了吗？

### ISSUE THREAD

**Issue by lbshold** [dodois/Doisnet#38]
今天开始，突然连接不上了，是出什么问题了吗？

**Comment by dodois** [comment]
This Server is suspended due to Bandwidth Over Usage. You cannot perform any operations for the Server !
Your Server was suspended on 23-12-2021 and it will be unsuspended on 16-01-2022

我无法连接到主服务器，感到无助，此问题非常棘手，正在寻求解决办法

**Comment by byebyemyk** [comment]
感谢作者，希望服务尽快回复，不行的话就做个限流吧

**Comment by Alphazer01214** [comment]
同，不过免费VPN能用这么久也不容易

**Comment by dodois** [comment]
成本太大，没有收入，不得不强制暂停免费使用

**Comment by lbshold** [comment]
您好：

doisnet 如何续费呢？


后续继续使用，如何付费呢？










在 2021-12-25 13:07:05，"dodois" ***@***.***> 写道：

成本太大，没有收入，不得不强制暂停免费使用

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
