### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by xinnie-the-pooh** [dodois/Doisnet#42]
我希望我可以向您的地址捐赠我所有的xmr，因为我的确有一点点。另外的，阁下在cn做这种是否有些危险。

**Comment by dodois** [comment]
With xmr, there is no risk

**Comment by xinnie-the-pooh** [comment]
我可以直接把我的钱包.key和password发给您吗，因为本地节点文件难以同步.里面应该还有0.2个

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: dodois ***@***.***>
发送时间: Friday, January 28, 2022 4:02:19 PM
收件人: dodois/Doisnet ***@***.***>
抄送: Winston Smith ***@***.***>; Author ***@***.***>
主题: Re: [dodois/Doisnet] 提问 (Issue #42)


With xmr, there is no risk

―

**Comment by dodois** [comment]
可以的

**Comment by xinnie-the-pooh** [comment]
这是我发出的地址：82bDF4GB8rnMek9gVJNAMRZirrHARGxj7b34T9HCvmm3VTpC5bQ7L1mhZbhG7wMs3aHMyKpoqbxgkEZMTG1Ax8S5T3oz84L
共计0.19xmr

**Comment by dodois** [comment]
已收到xmr，非常感谢您的慷慨捐赠！

**Comment by xinnie-the-pooh** [comment]
您好，如何获得礼品节点或附赠功能呢。

**Comment by dodois** [comment]
@xinnie-the-pooh 请通过邮箱私信我，您Doisnet客户端绑定的邮箱账号

**Comment by xinnie-the-pooh** [comment]
您的邮箱是什么呢，或者我该如何私信，我telegram是不可用的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: dodois ***@***.***>
发送时间: Monday, February 7, 2022 1:09:31 PM
收件人: dodois/Doisnet ***@***.***>
抄送: Winston Smith ***@***.***>; Mention ***@***.***>
主题: Re: [dodois/Doisnet] 提问 (Issue #42)


@xinnie-the-pooh<https://github.com/xinnie-the-pooh> 请通过邮箱私信我，您Doisnet客户端绑定的邮箱账号

―

**Comment by xinnie-the-pooh** [comment]
***@***.***      他可以收到来自vpn Clint 的验证码  是否可劳烦您向我的live邮箱发送附件📎？ 或您是否可以提供已知的可连通邮箱提供商名称    本邮件运营商提示的错误报告如下：

请通过其他方式(例如通过电话)与收件人联系，并让他们告诉其电子邮件管理员，当你的电子邮件系统尝试连接到其电子邮件系统时，其电子邮件系统拒绝来自你的电子邮件系统的连接。向他们提供如下所示的错误详细信息。可能仅收件人的电子邮件管理员能够解决此问题。

致电子邮件管理员
无法建立连接，因为目标计算机已主动拒绝该连接。出现此情形通常是因为尝试连接的服务在远程主机上处于不活动状态，即服务当前未运行任何服务器应用程序。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: dodois ***@***.***>
发送时间: Friday, February 11, 2022 10:41:45 AM
收件人: dodois/Doisnet ***@***.***>
抄送: Winston Smith ***@***.***>; Mention ***@***.***>
主题: Re: [dodois/Doisnet] 提问 (Issue #42)


***@***.******@***.***>

**Comment by xinnie-the-pooh** [comment]
这个是刚才疑似损坏的头 ：很抱歉再次打扰您，live邮箱貌似无法发送邮件到您的邮箱 ***@***.***

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Winston Smith ***@***.***>
发送时间: Friday, February 18, 2022 12:11:50 AM
收件人: dodois/Doisnet ***@***.***>
抄送: Winston Smith ***@***.***>; Your activity ***@***.***>
主题: Re: [dodois/Doisnet] 提问 (Issue #42)


***@***.*** 他可以收到来自vpn Clint 的验证码 是否可劳烦您向我的live邮箱发送附件📎？ 或您是否可以提供已知的可连通邮箱提供商名称 本邮件运营商提示的错误报告如下：

请通过其他方式(例如通过电话)与收件人联系，并让他们告诉其电子邮件管理员，当你的电子邮件系统尝试连接到其电子邮件系统时，其电子邮件系统拒绝来自你的电子邮件系统的连接。向他们提供如下所示的错误详细信息。可能仅收件人的电子邮件管理员能够解决此问题。

致电子邮件管理员
无法建立连接，因为目标计算机已主动拒绝该连接。出现此情形通常是因为尝试连接的服务在远程主机上处于不活动状态，即服务当前未运行任何服务器应用程序。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: dodois ***@***.***>
发送时间: Friday, February 11, 2022 10:41:45 AM
收件人: dodois/Doisnet ***@***.***>
抄送: Winston Smith ***@***.***>; Mention ***@***.***>
主题: Re: [dodois/Doisnet] 提问 (Issue #42)


***@***.******@***.***>
