### ISSUE TITLE
想请问一下 允许 局域网 链接  是什么功能啊

### ISSUE THREAD

**Issue by kylewuwu** [dodois/Doisnet#7]
想请问一下 允许 局域网 链接  是什么功能啊

**Comment by dodois** [comment]
此功能一般适用于高阶用户，简单解释如下：

*任何IP都可以连入，不允许的时候仅127.0.0.1或::1为目标地址时能连入*

**Comment by dodois** [comment]
简单场景 ```PC.B（ip: 192.168.0.2）``` 通过 ```PC.A（ip: 192.168.0.1）``` 上网
*PC.A 安装 ```Doisnet``` ,开启```允许局域网连接```， PC.B 设置代理服务器为```socks=192.168.0.1```, 端口号为：PC.A 代理服务器中显示的端口号(可能的值：8000或其他)*

此时 PC.B 就能流畅访问外网，而无需其他任何第三方工具

**Comment by kylewuwu** [comment]
> 简单场景 `PC.B（ip: 192.168.0.2）` 通过 `PC.A（ip: 192.168.0.1）` 上网
> _PC.A 安装 `Doisnet` ,开启`允许局域网连接`， PC.B 设置代理服务器为`socks=192.168.0.1`, 端口号为：PC.A 代理服务器中显示的端口号(可能的值：8000或其他)_
> 
> 此时 PC.B 就能流畅访问外网，而无需其他任何第三方工具

我开启了局域网链接后，在哪里能看到 端口是多少

**Comment by dodois** [comment]
@kylewuwu ```OnlineAnonymity 0.1.3```版本我们新增了 自定义端口及查看当前端口的能力 
![image](https://user-images.githubusercontent.com/73285310/119252053-8a27de80-bbdc-11eb-8007-33d0b6b947e5.png)
