### ISSUE TITLE
插件一直下载失败！

### ISSUE THREAD

**Issue by 1309919990** [dodois/Doisnet#8]
删除C:\Users\Administrator\AppData\Roaming\doisnet下的config.json后插件下载一直提示超时
![122](https://user-images.githubusercontent.com/20027229/118920969-eafbb080-b969-11eb-8a93-409c9be41e5b.png)
![123](https://user-images.githubusercontent.com/20027229/118920983-f353eb80-b969-11eb-909a-e818688b07b0.png)

**Comment by dodois** [comment]
@1309919990 [手动下载及安装插件](https://github.com/dodois/Doisnet/issues/9)

**Comment by 1309919990** [comment]
非常感谢！
